import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import Footer from "../components/footer/Footer";
import Header from "../components/header/Header";
import Introduction from "../components/introduction/Introduction";
import PaintCalculator from "../components/main/PaintCalculator";

const Home = () => {
  const [language, setLanguage] = useState("english");
  return (
    <div className="flex flex-col flex-grow">
      <Head>
        <title>Easy paint</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main data-testid="main">
        <Header />
        <Introduction />
        <PaintCalculator />
      </main>

      <footer >
        <Footer />
      </footer>
    </div>
  );
};

export default Home;
