import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import Header from "../components/header/Header";
import Introduction from "../components/introduction/Introduction";
import PaintCalculator from "../components/main/PaintCalculator";

const Home: NextPage = () => {
  const [language, setLanguage] = useState("english");
  return (
    <div>
      <Head>
        <title>Easy paint</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        <Introduction />
        <PaintCalculator />
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
